# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='By user')),
                ('order_id', models.IntegerField(verbose_name='For order')),
                ('payment_date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Payment date')),
                ('amount_paid', models.PositiveIntegerField(verbose_name='Amount paid')),
                ('payment_method', models.CharField(blank=True, choices=[('CH', 'Cash payment'), ('CD', 'Payment by card')], default='CH', max_length=2, verbose_name='Payment method')),
                ('account_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Account number')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
